version: "3"

services:
  vault:
    image: hashicorp/vault
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id=abcd
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
  configure:
    build:
      dockerfile: Dockerfile
    command: /usr/bin/configure.sh
    depends_on:
      - vault
      - postgres
    restart: "no"
  service:
    build:
      dockerfile: Dockerfile
    command: /usr/bin/service.sh
    depends_on:
      - vault
      - postgres
